### ISSUE TITLE
Pfam dataset version and preprocess

### ISSUE THREAD

**Issue by apeterswu** [songlab-cal/tape#104]
Hi, 

For your great work, I am curious about the pre-training dataset Pfam. 
What's the specific version of Pfam dataset and the detailed preprocessing steps?

I have downloaded the Pfam27.0 and Pfam32.0 version, but the data size is largely different.

**Comment by thomas-a-neil** [comment]
Did you download Pfam-full? Our pretraining dataset is Pfam-A.fasta from the Pfam32.0 release (which was "current release" when we downloaded in March 2019). Preprocessing included serialization and splitting into train/validation/test (a random split and a holdout split) as described in our paper.

**Comment by rmrao** [comment]
Actually I think our pretraining dataset is slightly less than Pfam32.0 (we downloaded the "current release" between the 31.0 and 32.0 releases).

**Comment by thomas-a-neil** [comment]
If it's helpful, see #75 for a discussion of mapping back to Pfam ids using the Pfam32 release (which should be a superset of our pretraining set)

**Comment by apeterswu** [comment]
Sorry for the late response and thanks for your information. I will check the "current release" of Pfam-A.faasta.
