### ISSUE TITLE
some wrong with url of config.json

### ISSUE THREAD

**Issue by willow-yll** [songlab-cal/tape#112]
Hi~
I was trying to run tape-embed, but received the following error message

![image](https://user-images.githubusercontent.com/79819922/129171148-a6579b0e-8c09-40dc-8ad0-b22f9e43d495.png)
 

and 

![image](https://user-images.githubusercontent.com/79819922/129171476-9832e0b3-aeaa-4efe-b370-8c1606dd7b56.png)

![image](https://user-images.githubusercontent.com/79819922/129171538-9f4c858d-e6f7-4229-a71a-8df896cf1474.png)

**Comment by ax-he** [comment]
I faced the same question.
And the configuration file of bert-base cannot open either.
![image](https://user-images.githubusercontent.com/35193352/129176161-460d3d96-0201-49e7-8b34-91badbbdf920.png)

**Comment by willow-yll** [comment]
> I faced the same question.
> And the configuration file of bert-base cannot open either.
> ![image](https://user-images.githubusercontent.com/35193352/129176161-460d3d96-0201-49e7-8b34-91badbbdf920.png)



> I faced the same question.
> And the configuration file of bert-base cannot open either.
> ![image](https://user-images.githubusercontent.com/35193352/129176161-460d3d96-0201-49e7-8b34-91badbbdf920.png)

maybe I find a right url , but I do not know where to modify

**Comment by ax-he** [comment]
> > I faced the same question.
> > And the configuration file of bert-base cannot open either.
> > ![image](https://user-images.githubusercontent.com/35193352/129176161-460d3d96-0201-49e7-8b34-91badbbdf920.png)
> 
> > I faced the same question.
> > And the configuration file of bert-base cannot open either.
> > ![image](https://user-images.githubusercontent.com/35193352/129176161-460d3d96-0201-49e7-8b34-91badbbdf920.png)
> 
> maybe I find a right url , but I do not know where to modify

I tried the command `tape-embed transformer my_input.fasta output_filename.npz bert-base`  and `tape-embed unirep my_input.fasta output_filename.npz babbler-1900 --tokenizer unirep`, but both of them failed.

**Comment by rmrao** [comment]
Hi, we recently had to change the s3 bucket where these were stored, which resulted in a new url for download. Please make sure you have the latest version installed (pull from GitHub / upgrade from pip). If this issue persists, please let us know whether you installed tape via GitHub or pip and we will follow up.

**Comment by ax-he** [comment]
> Hi, we recently had to change the s3 bucket where these were stored, which resulted in a new url for download. Please make sure you have the latest version installed (pull from GitHub / upgrade from pip). If this issue persists, please let us know whether you installed tape via GitHub or pip and we will follow up.

Thanks for your quick reply!
I downloaded the "new-s3-bucket" branch. But the command `tape-embed` still links to the previous url.
![N8_(E {%}}3`F5RLXCCAN3E](https://user-images.githubusercontent.com/35193352/129253150-21c0dd17-8290-4c59-8dc9-3a04cd59d531.png)
I installed tape via pip.
![OQ ~HO$0KDYW}OWMJ1W{APH](https://user-images.githubusercontent.com/35193352/129255760-144917c3-67f6-4f62-b378-e381f36f1816.png)

Is there anything wrong with my operation or environment?
P.S., when I executed `./download_data.sh`, the url was correct as it was linked to http://s3.amazonaws.com/songlabdata/... 
and I can open the website https://s3.amazonaws.com/songlabdata/proteindata/pytorch-models/bert-base-config.json

**Comment by notes-ml** [comment]
Install directly from the repo:
`pip install git+https://github.com/songlab-cal/tape.git`

if already installed add flags `--upgrade --force-reinstall `

**Comment by rmrao** [comment]
yes sorry, looks like the pip package has not been updated (my mistake, thought it had been modified), opened an issue (#113), will fix by this weekend.

**Comment by willow-yll** [comment]
When I run "python main.py transformer my_input.fasta my_output_.npz bert-base – –tokenizer iupac"  I received the wrong message upon .How can I run the .py in Github? Thank u !!!

**Comment by rmrao** [comment]
@willow-yll please open a new issue with a description and the output the error you are actually getting.
