### ISSUE TITLE
How to run with file in Gitlab

### ISSUE THREAD

**Issue by willow-yll** [songlab-cal/tape#114]
Hello, I want to add a new task  to use your method , but I do not know how to deal with my data to generate the needed data such as 'msak'.   
and I want to use your method to get embedding of my protein sequence, can I simply use the code like this?
![image](https://user-images.githubusercontent.com/79819922/129324760-734789d2-9d91-40e6-a6b2-2cc9ad39258a.png)

**Comment by willow-yll** [comment]
In fact, I don’t know how to apply the classifier to classify, and the order of running the code .....

**Comment by ax-he** [comment]
copy the codes into a new python file and run it.
for example, if the codes are copied into a file named as "test.py", then you can use `python test.py` to run.

**Comment by willow-yll** [comment]
> copy the codes into a new python file and run it.
> for example, if the codes are copied into a file named as "test.py", then you can use `python test.py` to run.

oh thank u....  I mean, which file can be run to add task and make predictions, I tried to run ‘ add task.py’ first, then run the calss ‘run_train’ of training.py, but there seems to be an error

**Comment by rmrao** [comment]
If you just want to get embeddings, you can use the tape-embed command. Add the help flag to get the options.

The add_task.py is an example that you would need to modify with your appropriate data / model.

**Comment by willow-yll** [comment]
thank u , I will try

**Comment by willow-yll** [comment]
I run main.py run_embed() and erroe message like this 
![image](https://user-images.githubusercontent.com/79819922/129682211-fd9f5a3c-09d1-4b00-b242-414bed4a6b71.png)
So...Maybe I have to run registry.py to add embed task first?

**Comment by willow-yll** [comment]
> copy the codes into a new python file and run it.
> for example, if the codes are copied into a file named as "test.py", then you can use `python test.py` to run.

hello! Do you run  tape-embed command  successfully？

**Comment by ax-he** [comment]
> > copy the codes into a new python file and run it.
> > for example, if the codes are copied into a file named as "test.py", then you can use `python test.py` to run.
> 
> hello! Do you run tape-embed command successfully？

yes, use the command `tape-embed transformer my_input.fasta output_filename.npz bert-base` or `tape-embed unirep my_input.fasta output_filename.npz babbler-1900 --tokenizer unirep`

**Comment by rmrao** [comment]
I'm not totally sure if the issue is resolved - if it is, could you please close the issue? If not, let me know what's going wrong!
