### ISSUE TITLE
about ProteinBertModel

### ISSUE THREAD

**Issue by viko-3** [songlab-cal/tape#115]
I want use pretrain model to embedding proteins, but I meet some problems
The code are as foloows:
```
import torch
from tape import ProteinBertModel, TAPETokenizer
model = ProteinBertModel.from_pretrained('bert-base')
tokenizer = TAPETokenizer(vocab='iupac')  # iupac is the vocab for TAPE models, use unirep for the UniRep model

# Pfam Family: Hexapep, Clan: CL0536
sequence = 'GCTVEDRCLIGMGAILLNGCVIGSGSLVAAGALITQ'
token_ids = torch.tensor([tokenizer.encode(sequence)])
output = model(token_ids)
sequence_output = output[0]
pooled_output = output[1]
```
Thr bug code is: 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    model = ProteinBertModel.from_pretrained('bert-base')
  File "/home/cyy/Code/tape/tape/models/modeling_utils.py", line 478, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/cyy/Code/tape/tape/models/modeling_utils.py", line 172, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "/home/cyy/Code/tape/tape/models/modeling_utils.py", line 202, in from_json_file
    return cls.from_dict(json.loads(text))
  File "/home/cyy/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/cyy/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/cyy/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I don't know why

**Comment by yuzhiguo07** [comment]
I got the same error

**Comment by rmrao** [comment]
We recently had to update the AWS bucket where models were stored - please make sure you're on the most recent version. The pypi repository hasn't been updated, so pull/install from git.

If that doesn't fix the issue, please try running `model = ProteinBertModel.from_pretrained("bert-base", force_download=True)`.

**Comment by EstherBear** [comment]
> We recently had to update the AWS bucket where models were stored - please make sure you're on the most recent version. The pypi repository hasn't been updated, so pull/install from git.
> 
> If that doesn't fix the issue, please try running `model = ProteinBertModel.from_pretrained("bert-base", force_download=True)`.

I got the same error when i try running model = ProteinBertModel.from_pretrained("bert-base", force_download=True).

**Comment by rmrao** [comment]
Can you run the following and report the messages that get printed?

```python
import logging
from tape import ProteinBertModel

logging.basicConfig(level=logging.DEBUG)
model = ProteinBertModel.from_pretrained("bert-base")
```

**Comment by viko-3** [comment]
> Can you run the following and report the messages that get printed?
> 
> ```python
> import logging
> from tape import ProteinBertModel
> 
> logging.basicConfig(level=logging.DEBUG)
> model = ProteinBertModel.from_pretrained("bert-base")
> ```

`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com:443
DEBUG:urllib3.connectionpool:https://s3.amazonaws.com:443 "HEAD /songlabdata/proteindata/pytorch-models/bert-base-config.json HTTP/1.1" 200 0
INFO:tape.models.modeling_utils:loading configuration file https://s3.amazonaws.com/songlabdata/proteindata/pytorch-models/bert-base-config.json from cache at /home/cyy/.cache/torch/protein_models/fbb05edff0ffa844a729a04850272a1f8973bc002526f6615ad113a5f5aacd36.05edb4ed225e1907a3878f9d68b275d79e025b667555aa94a086e27cb5c591e0
INFO:tape.models.modeling_utils:Model config {
  "attention_probs_dropout_prob": 0.1,
  "base_model": "transformer",
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "input_size": 768,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 8192,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_size": 768,
  "pruned_heads": {},
  "torchscript": false,
  "type_vocab_size": 1,
  "vocab_size": 30
}

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com:443
DEBUG:urllib3.connectionpool:https://s3.amazonaws.com:443 "HEAD /songlabdata/proteindata/pytorch-models/bert-base-pytorch_model.bin HTTP/1.1" 200 0
INFO:tape.models.modeling_utils:loading weights file https://s3.amazonaws.com/songlabdata/proteindata/pytorch-models/bert-base-pytorch_model.bin from cache at /home/cyy/.cache/torch/protein_models/2ed84d28db0a61af4cd2dd3f2ccdd3ee45b1533547a8e1213840af895e2fa8d1.8206daaea9be2736b6ccde432df9dc3dbb8c3233b47f07688d6ff38d74258d22`


I run the code and there is the printed message.

**Comment by viko-3** [comment]
> I want use pretrain model to embedding proteins, but I meet some problems
> The code are as foloows:
> 
> ```
> import torch
> from tape import ProteinBertModel, TAPETokenizer
> model = ProteinBertModel.from_pretrained('bert-base')
> tokenizer = TAPETokenizer(vocab='iupac')  # iupac is the vocab for TAPE models, use unirep for the UniRep model
> 
> # Pfam Family: Hexapep, Clan: CL0536
> sequence = 'GCTVEDRCLIGMGAILLNGCVIGSGSLVAAGALITQ'
> token_ids = torch.tensor([tokenizer.encode(sequence)])
> output = model(token_ids)
> sequence_output = output[0]
> pooled_output = output[1]
> ```
> 
> Thr bug code is:
> Traceback (most recent call last):
> File "test.py", line 3, in
> model = ProteinBertModel.from_pretrained('bert-base')
> File "/home/cyy/Code/tape/tape/models/modeling_utils.py", line 478, in from_pretrained
> config, model_kwargs = cls.config_class.from_pretrained(
> File "/home/cyy/Code/tape/tape/models/modeling_utils.py", line 172, in from_pretrained
> config = cls.from_json_file(resolved_config_file)
> File "/home/cyy/Code/tape/tape/models/modeling_utils.py", line 202, in from_json_file
> return cls.from_dict(json.loads(text))
> File "/home/cyy/anaconda3/lib/python3.8/json/**init**.py", line 357, in loads
> return _default_decoder.decode(s)
> File "/home/cyy/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/home/cyy/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> I don't know why

I reinstall the environment and rerun the same code, but there is no bug now. I feel so surprised!

**Comment by kc199** [comment]
Hi, was there a fix for this?  I tried reinstalling the environment, and model = ProteinBertModel.from_pretrained("bert-base", force_download=True), but still obtained the same error- "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)".

Would appreciate any guidance- thanks so much!

**Comment by rmrao** [comment]
I'm assuming that if it's working for @Cyy1216 after reinstall then it's probably an issue with the environment not updating correctly.

Could you run this code:
```python
import logging
from tape import ProteinBertModel

logging.basicConfig(level=logging.DEBUG)
model = ProteinBertModel.from_pretrained("bert-base")
```

Can you also specify how you installed tape? (i.e. via pip, via github, etc.)

**Comment by kc199** [comment]
Thanks for the tips- below is the output from the code you suggested, with the error at the bottom.  I installed with pip exactly as written on the github (pip install tape_proteins), would you recommend installing from github?  If so, could you specify the command to do this?  Thanks again!

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com:443
DEBUG:urllib3.connectionpool:https://s3.amazonaws.com:443 "HEAD /proteindata/pytorch-models/bert-base-config.json HTTP/1.1" 403 0
INFO:tape.models.modeling_utils:loading configuration file https://s3.amazonaws.com/proteindata/pytorch-models/bert-base-config.json from cache at /home/unix/ckrishna/.cache/torch/protein_models/6373bfcc1f9755cd1b90c75a4c82e5b6ace8db121253e86653b69c3fec08ed04
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/unix/ckrishna/.local/lib/python3.8/site-packages/tape/models/modeling_utils.py", line 467, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/unix/ckrishna/.local/lib/python3.8/site-packages/tape/models/modeling_utils.py", line 172, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "/home/unix/ckrishna/.local/lib/python3.8/site-packages/tape/models/modeling_utils.py", line 202, in from_json_file
    return cls.from_dict(json.loads(text))
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2020.07/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2020.07/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/anaconda3_2020.07/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kc199** [comment]
@rmrao , just following up- I installed from git using the command in this thread- https://github.com/songlab-cal/tape/issues/112, pip install git+https://github.com/songlab-cal/tape.git.  Then everything worked as expected!  Seems there is an issue when installing with pip.

**Comment by rmrao** [comment]
Yes sorry! I've been meaning to fix it, and will update the pip repository when I get the chance... Closing this issue for now.
