### ISSUE TITLE
Issue downloading weights

### ISSUE THREAD

**Issue by rmwu** [songlab-cal/tape#117]
Hello! I've been using your repository and pretrained weights for some time now, but this morning I received the error:

```Couldn't reach server at 'https://s3.amazonaws.com/proteindata/pytorch-models/bert-base-config.json' to download pretrained model configuration file.```

The line that caused this issue was ```ProteinBertModel.from_pretrained("bert-base")```

Is this just a temporary issue with the hosting, or may we permanently download the weights/config file for use later?

**Comment by thomas-a-neil** [comment]
We recently pushed an update to the data hosting. You should be able to pip
install the latest version (or pull from the repo and build) to point to
the new s3 repo

**Comment by rmwu** [comment]
Thank you!

**Comment by asmaanagia3-ops** [comment]
https://m.facebook.com/login/identify/?cah=2&rwtsid=envY7ehCJuqMd52g9#
