### ISSUE TITLE
cannot import tape

### ISSUE THREAD

**Issue by willow-yll** [songlab-cal/tape#124]
I install tape use "pip install tape_proteins"and it shows that 
![图片](https://user-images.githubusercontent.com/79819922/156933350-fab3ef39-0566-4bdc-9560-ed527bd77d6a.png)
![图片](https://user-images.githubusercontent.com/79819922/156933355-b549fe9d-b581-405c-8e26-c6669806f8dd.png)
![图片](https://user-images.githubusercontent.com/79819922/156933366-24a8997f-eec7-43f8-b1b4-2eac2c731862.png)
but when "import tape" or "import tape_proteins" 
it shows that 
![图片](https://user-images.githubusercontent.com/79819922/156933394-66353232-49ee-4f35-9113-5139e5ec6aa4.png)

**Comment by rmrao** [comment]
Could you repeatedly run `pip uninstall tape_proteins` until pip says it's not installed? You may have to run it multiple times. Then try running `pip install tape_proteins`.

**Comment by willow-yll** [comment]
thank you !!!!  It is resolved!
