### ISSUE TITLE
bert-base embeddings

### ISSUE THREAD

**Issue by KarinBrisker** [songlab-cal/tape#13]
I tried to run the following command:
_tape-embed unirep my_input.fasta output_filename.npz **bert-base** --tokenizer unirep --full_sequence_embed_

why bert-base embedding not working and only 1900 dim embeddings?

thanks!

**Comment by RensDimmendaal** [comment]
You might want to try using the . "iupac" tokenizer.

in the readme it mentions the following in the hugging face api section:
```python
tokenizer = TAPETokenizer(vocab='iupac')  # iupac is the vocab for TAPE models, use unirep for the UniRep model
```

**Comment by rmrao** [comment]
You also have to switch the model type to transformer. So the command should be `tape-embed transformer input_file output_file bert-base`. ‘iupac’ is the default tokenizer so you can pass it in or not.

**Comment by KarinBrisker** [comment]
I run it as you said : 
> tape-embed transformer input.fasta bert_output.npz bert-base --full_sequence_embed

(I added the flag _--full_sequence_embed_, because I want embeddings per amino-acid)

but I get this output: 

>  Traceback (most recent call last):
>   File "/home/nlp/dahanka1/anaconda3/bin/tape-embed", line 8, in <module>
>     sys.exit(run_embed())
>   File "/home/nlp/dahanka1/anaconda3/lib/python3.6/site-packages/tape/main.py", line 232, in run_embed
>     training.run_embed(**embed_args)
>   File "/home/nlp/dahanka1/anaconda3/lib/python3.6/site-packages/tape/training.py", line 654, in run_embed
>     npzfile.savez(**to_save)
>   File "/home/nlp/dahanka1/anaconda3/lib/python3.6/site-packages/tape/utils/utils.py", line 283, in savez
>     fmt.write_array(fid, np.asanyarray(val), allow_pickle=True)
>   File "/home/nlp/dahanka1/anaconda3/lib/python3.6/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
>     return array(a, dtype, copy=False, order=order, subok=True)
> ValueError: could not broadcast input array from shape (768,768) into shape (768)

Maybe your bert model is not supporting this flag?

**Comment by KarinBrisker** [comment]
Maybe the solution is to change the config "output_hidden_states": false to True?

**Comment by rmrao** [comment]
Hmm. What version of numpy are you using? That shouldn't be an issue. I'll try to debug and see if I get the same error.

**Comment by KarinBrisker** [comment]
Thank you!
numpy version : _1.17.4_

**Comment by KarinBrisker** [comment]
notice that it tried to convert (768,768) into shape (768)
isn't it a logical problem?

**Comment by rmrao** [comment]
I'm actually having trouble reproducing this error. I'm also using numpy version 1.17.4 and python 3.6. Running the same command on my own fasta file completes successfully without issue. Are you able to provide your fasta file? Alternatively, if you download one of our datasets (e.g. fluorescence), are you able run successfully on that?

I'm not sure why it's trying to save an array of 768 x 768. None of the returned tensors there should be that size.

**Comment by KarinBrisker** [comment]
Ok, I debugged the code and found out that _val_ is a tuple.
The first element is a tensor (protein_len, 768) and the second (768, )
So I changed the code to:                 

with open(self.tmpfile, 'wb') as fid:
                    fmt.write_array(fid, np.asanyarray **(val[0])**, allow_pickle=True)
                self.zip.write(self.tmpfile, arcname=fname)

Is it ok?
Thank you for your fast reply!

**Comment by rmrao** [comment]
So val *is* supposed to be a tuple of length 2, containing the full sequence representation at `val[0]` and the pooled representation at `val[1]`. This seems to work fine for me when saving. I'm curious what the specific issue is that causes this. If you're able to provide your data, I'd be happy to see if I can reproduce the error (you can email it to me at rmrao@berkeley.edu or upload to google drive /etc.). Of course I understand if you can't share your data.

**Comment by rmrao** [comment]
Ok I am now getting the same issue. Thanks for sending the data. Will try and figure out what causes it.

**Comment by rmrao** [comment]
Found the issue, numpy didn't like it if there was a protein of length 768 in the dataset. Should be fixed now. Note that this slightly changes how the save file is returned (each entry will be a dictionary with keys, but it should be straightforward enough).

**Comment by KarinBrisker** [comment]
awesome, thanks!
