### ISSUE TITLE
tape-embed  error

### ISSUE THREAD

**Issue by Kevin-chen-sheng** [songlab-cal/tape#16]
![image](https://user-images.githubusercontent.com/52196486/71143515-cc195c00-2255-11ea-81d2-a408b94beeb9.png)
No errors were reported, but the results were clearly wrong

**Comment by wzcui** [comment]
I also encountered the same problem and didn't know how to solve it.

**Comment by rmrao** [comment]
Does it work if you use bert embeddings? Command should be `tape-embed transformer <input_file> <output_file> bert-base`.

**Comment by rmrao** [comment]
Oh actually I suspect this is related to #7. There may be a bug when there are > 10k sequences in the fasta dataset.

**Comment by rmrao** [comment]
Just pushed an attempted fix for #7. If you try to pull and run again, let me know if it fixed the issue.

**Comment by Kevin-chen-sheng** [comment]
![image](https://user-images.githubusercontent.com/52196486/71227900-9474e780-231b-11ea-8405-6763269de477.png)

I thought it was biopython that caused the problem and reinstalled it, but it still didn't work
![image](https://user-images.githubusercontent.com/52196486/71228008-eae22600-231b-11ea-88eb-c65c3bc67968.png)

**Comment by binarywz** [comment]
I set the batch_size --batch_size 100, it works.

**Comment by Kevin-chen-sheng** [comment]
> I set the batch_size --batch_size 100, it works.
There should be no wrong point in the batch, and when the wrong point is met, the error will be reported again.I tried, but it didn't work.

**Comment by Kevin-chen-sheng** [comment]
![image](https://user-images.githubusercontent.com/52196486/71235650-bbd9ad80-2337-11ea-8c44-b24c253f0928.png)


> Just pushed an attempted fix for #7. If you try to pull and run again, let me know if it fixed the issue.

Still can't solve the problem

**Comment by rmrao** [comment]
Can you send me your data file? It is hard for me to debug without any more information. You can email it to me at rmrao@berkeley.edu.

**Comment by Kevin-chen-sheng** [comment]
> Can you send me your data file? It is hard for me to debug without any more information. You can email it to me at [rmrao@berkeley.edu](mailto:rmrao@berkeley.edu).

Ok. I'll send it to you by qq email.

**Comment by rmrao** [comment]
@Kevin-chen-sheng I was able to run this without an issue by reducing batch size. It is odd that it failed without giving you an explicit CUDA OOM error message. I added some code (#22) that should hopefully give you an explicit warning. You should be able to run this if you reduce batch size sufficiently (`tape-embed unirep PDB_train.fasta output_filename babbler-1900 --tokenizer unirep --batch_size <NUM>`)

**Comment by Kevin-chen-sheng** [comment]
Thank you. When I set it to 2, it works.

**Comment by rmrao** [comment]
Sounds good, seems like things are working for everyone then, so I'm closing this.
