### ISSUE TITLE
tape-train error

### ISSUE THREAD

**Issue by binarywz** [songlab-cal/tape#18]
![image](https://user-images.githubusercontent.com/58714070/71239323-378c2800-2341-11ea-9405-c1a342d94ec4.png)
When i use `tape-train transformer masked_language_modeling --batch_size 16 --learning_rate 0.001 --warmup_steps 100`, it works. But use `tape-train lstm language_modeling --batch_size 16 --learning_rate 0.001 --warmup_steps 100`, error occured. I want to kown how to train lstm model.

**Comment by rmrao** [comment]
This looks like a bug in the LanguageModelingDataset. I’ll take a look and see what the issue is.

**Comment by binarywz** [comment]
Could you tell me when you fix it? Thanks.

**Comment by rmrao** [comment]
Yes. I am out of town for the next 2-3 days so it will probably be on Monday.

**Comment by binarywz** [comment]
OK! Thanks.

**Comment by rmrao** [comment]
@cuiwz should be fixed
