### ISSUE TITLE
About LSTM pretrained model

### ISSUE THREAD

**Issue by xnuohz** [songlab-cal/tape#19]
Could you add LSTM pretrained model? I want to use it for some tasks. Thanks :)

**Comment by rmrao** [comment]
Yes, we plan to, but we have to actually run the pretraining with the pytorch version, which will probably take a while (have to find some free compute then actually run it, so it’ll be at least a week or two).

**Comment by rmrao** [comment]
Haven't been able to free up a lot of compute recently - so it'll take longer to get this than I anticipated. We'll definitely put it up at some point, but I can't promise a specific timeline.

**Comment by wengong-jin** [comment]
Has the pre-trained LSTM model uploaded yet?

**Comment by rmrao** [comment]
I haven't been able to justify using 4 GPUs for a week to train this model... Plausibly over the summer Berkeley compute will free up a little bit and I can train it then.

**Comment by jcdelpiano** [comment]
Hello, have you been able to work on the pre-trained LSTM model? Many thanks!

**Comment by rmrao** [comment]
I've started training it. Should ideally finish in 1-2 days, but may take longer if there are issues during training. I'll try to have it uploaded in a week or two at most.

**Comment by jcdelpiano** [comment]
Hello again! any news about the LSTM model? thank you for your help and time!

**Comment by rmrao** [comment]
Ok realistically this isn't going to happen, I don't have the time or compute to train this long enough and test it to make sure the weights are reasonable. If you really want an LSTM model I'd recommend using SeqVec from the Rostlab ([here](https://github.com/rostlab/SeqVec))
