### ISSUE TITLE
About python command

### ISSUE THREAD

**Issue by binarywz** [songlab-cal/tape#20]
I want to use python command to run a task, how to do?

**Comment by rmrao** [comment]
To *train* a task? We provide the `tape-train` / `tape-train-distributed` commands for that (these are just entrypoints to python and are effectively using the python command). You can also look at the two examples in the `examples/` folder, which should you how to import the main functions and add them to your own file, which you can run with the `python` command.

**Comment by binarywz** [comment]
OK! Thanks!
