### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by Kevin-chen-sheng** [songlab-cal/tape#24]
The model was successfully trained by tape-train, and finally, a folder was created under the results folder. In this folder, I could not find anything about the evaluation of the results, such as accuracy, etc.What should I do to get the evaluation?

**Comment by rmrao** [comment]
You can use the `tape-eval` function - however the eval is a little buggy at the moment unfortunately. It's on my list of things to do. I should get around to it sometime in the next week. I will update the README with instructions when I have everything sorted.

**Comment by SorteKanin** [comment]
Please do! If you could do it faster than next week that would be greatly appreciated. I currently can't run evaluation for the UniRep model. I get the following error:

```
Evaluation:   0%|                                                                                                    | 0/1 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "C:\Python37\Scripts\tape-eval-script.py", line 11, in <module>
    load_entry_point('tape-proteins==0.3', 'console_scripts', 'tape-eval')()
  File "c:\python37\lib\site-packages\tape\main.py", line 213, in run_eval
    return training.run_eval(**eval_args)
  File "c:\python37\lib\site-packages\tape\training.py", line 593, in run_eval
    save_outputs = run_eval_epoch(valid_loader, runner, is_master)
  File "c:\python37\lib\site-packages\tape\training.py", line 382, in run_eval_epoch
    save_outputs.append(_get_outputs_to_save(batch, outputs))
  File "c:\python37\lib\site-packages\tape\training.py", line 354, in _get_outputs_to_save
    outputs = outputs.cpu().numpy()
AttributeError: 'tuple' object has no attribute 'cpu'
```

**Comment by rmrao** [comment]
So one other note - if you're just trying to evaluate the results of pretraining, `tape-eval` isn't really a great option. At best I could have it tell you language modeling accuracy / perplexity, but empirically this does not seem to have a strong correlation with performance on downstream tasks.

If you want to evaluate performance of a language model, your best bet is to use `tape-train`/`tape-train-distributed` along with the `--from_pretrained` flag to train a downstream task based on the pretrained model (this will run validation passes as well). `tape-eval` is only needed to run the test set of a task.

Regardless, I'll aim to have `tape-eval` fixed and a section in the README about evaluating models by the end of the week.

**Comment by SorteKanin** [comment]
Thanks for the info :). When running tape-train, I only see validation losses though, no accuracies or other metrics, to compare against the metric given in the readme for the different tasks and models.

**Comment by rmrao** [comment]
Ah yeah I'll fix that - API got updated a lot in the week before release and metrics were taken out for initial simplicity. Should be easy to add them back in.

**Comment by rmrao** [comment]
Both issues should be fixed by #25, which adds metrics to the training loop and fixes the `tape-eval` command. I have also added sections to the README on evaluating a language model, training a downstream model, and evaluating a downstream model. Let me know if there is anything missing.

The one missing metric for `tape-eval` is Precision @ L/5 for contact prediction (this will be reported during train/eval but it is missing during test). I will fix this in the future, but wanted to get this out ASAP since all other tasks should be good to go.

**Comment by Kevin-chen-sheng** [comment]
![image](https://user-images.githubusercontent.com/52196486/72325118-68b10b80-36e7-11ea-87de-cd5a2e292220.png)
Ran tape.eval and got this error. This confused me.

**Comment by rmrao** [comment]
This seems like a problem in your data? Do you have a lowercase 'v' in your test set?

**Comment by rmrao** [comment]
Closing because no response.
