### ISSUE TITLE
How to train models on new data (FASTA)

### ISSUE THREAD

**Issue by faruuk** [songlab-cal/tape#27]
I have some specific data, that I want the model to train on. The data is stored in FASTA format. How can I use the interfaces provided to train the models on my custom data?

**Comment by rmrao** [comment]
Please follow the example in [examples/adding_task.py](https://github.com/songlab-cal/tape/blob/master/examples/adding_task.py). This example shows how to add a custom task. Note that the while it uses data stored in the LMDB format, the created Dataset is simply an arbitrary pytorch dataset. Therefore, you can simply replace loading of LMDB data with loading of FASTA data.
