### ISSUE TITLE
Reverse sequence for LSTM model

### ISSUE THREAD

**Issue by karnawhat** [songlab-cal/tape#38]
Within `LSTMEncoder`, when attempting to compute the reverse outputs though theLSTM with reversed inputs (aka the `reverse_lstm` layers), reversing the sequence does not return anything when `input_mask=None` (see below). This is because of incorrect indentation on L127.

https://github.com/songlab-cal/tape/blob/2e5bfa2249274392baf045df7de1490e92d47ed1/tape/models/modeling_lstm.py#L114-L127

**Comment by rmrao** [comment]
Yup looks like a bug!
