### ISSUE TITLE
tape-eval error 

### ISSUE THREAD

**Issue by brendanyap** [songlab-cal/tape#42]
When I run `tape-eval transformer secondary_structure results/secondary_structure_transformer_20-03-10-17-00-07_837748/ --metrics mae --split casp12` it gives me an error about the metric not existing in the `metric_name_mapping`.

![Screenshot from 2020-03-10 16-38-56](https://user-images.githubusercontent.com/38015679/76371017-37337580-630f-11ea-955f-392074fe3e16.png)

I used `tape-train transformer secondary_structure --batch_size=4 --gradient_accumulation_steps=4 --num_train_epochs=1` to quickly train a model to test out `tape-eval`. 

I've tried adding the following to the top of main.py
```
from metrics import *
from . import metrics
```

and this to the top of training.py:
```
from .metrics import *
```

since it seems the metrics were not getting registered, but I still got the same error message. Adding `cls.metric_name_mapping` to line 194 of tape/registry.py, and results in printing an empty dictionary.

**Comment by rmrao** [comment]
Hi Brendan,

I'm not able to reproduce this error - I just tried exactly the commands you used and it seems to load properly. I'm not sure if you've made further modifications, but if so could you try ensuring that you're working with an unmodified version of master first?

I did get a separate error (as expected) since `mae` is not a sensible metric for secondary structure, but it did load the metric just fine.

**Comment by brendanyap** [comment]
Hey Roshan,

I still get this error if I do a fresh `pip install tape-proteins` and try the above. I think you're right though that I'm not working with an up-to-date master. In particular, it seems that the changes from https://github.com/songlab-cal/tape/commit/13dc981eb43d1b020056c4087dcf1c132e330427 aren't present in the `pip`-installed version. `tape/__init.py__` is missing line 2 in the fresh `pip` install:

```
from . import metrics  # noqa: F401
```

Adding this line to my version solves the problem. I still get some other errors, though, and I think it's probably because of the other fixes in the above commit. I tried updating `tape-proteins` with pip, but this didn't make any changes. Is the package updated in pip?

**Comment by rmrao** [comment]
Ah yes I must not have updated it in pip after the most recent fixes. If you clone master it should work. I will update pip in the next day or two.

**Comment by brendanyap** [comment]
Thanks!

**Comment by rmrao** [comment]
Finally got around to fixing this in the latest release.
