### ISSUE TITLE
Unable to locate data_utils module

### ISSUE THREAD

**Issue by jessevig** [songlab-cal/tape#47]
Thank you for this incredibly useful and well-designed library! I couldn’t find the data_utils module that is imported in the preprocessing scripts. Would it be possible to include that in the repo as well? Many thanks in advance!

**Comment by jessevig** [comment]
I was able to find a version of data_utils in https://github.com/songlab-cal/tape-neurips2019. Do you know if that version is what was use to generate the datasets?

**Comment by rmrao** [comment]
Yes that was what we used to create the datasets in the original paper. We also provide links to the raw JSON and LMDB files in our README.

**Comment by jessevig** [comment]
Thanks!
