### ISSUE TITLE
Corrupted stability dataset (raw format)

### ISSUE THREAD

**Issue by ikedim01** [songlab-cal/tape#49]
I downloaded stability.tar.gz using the link on the readme page.
Uncompressed using archive manager on Ubuntu 18.04.
stability_train.json and stability_valid.json look OK
but stability_test looks corrupted.

**Comment by ikedim01** [comment]
After a little more looking, it appears that the stability_test.json file is actually a gzipped tar file
containing another copy of stability_train.json and stability_valid.json.

**Comment by rmrao** [comment]
Oh strange... very odd. Someone pointed this out for fluorescence. Looks like the same issue with stability data. I’ll have to re-upload it.

-Roshan

**Comment by ikedim01** [comment]
Any updates?

**Comment by ikedim01** [comment]
Are you going to fix this in the near future?
Doesn't seem like it should take that long to re-upload a file ...

**Comment by rmrao** [comment]
Sorry, took a bit to get around to this. Should be fixed now.

**Comment by ikedim01** [comment]
Looks OK now, thanks!
