### ISSUE TITLE
Question about onehot contact prediction model

### ISSUE THREAD

**Issue by jessevig** [songlab-cal/tape#52]
Hi,
I was able able to get the onehot model working for contact prediction (after making a few changes, like setting defaults in config class), however the performance is much lower (~0.06 precision@L/5) than reported in the paper. 

If I'm understanding the code correctly, the [pytorch version of the contact prediction head](https://github.com/songlab-cal/tape/blob/ab49d242a81f7a1d0b291507c8a0b0f5fd6d960c/tape/models/modeling_utils.py#L829) uses a simple linear classifier, whereas the [original implementation ](https://github.com/songlab-cal/tape-neurips2019/blob/3f55c784750207d28327ac69c39f892abf548c06/tape/task_models/ResidueResidueContactPredictor.py#L11) also included convolutional layers, as described in the paper.

Is this understanding correct?

Thanks!

**Comment by rmrao** [comment]
Yes, I did not add the additional convolutional model for contact prediction to the pytorch implementation.
