### ISSUE TITLE
what does the from tape import data_utils  refer?

### ISSUE THREAD

**Issue by HadXu** [songlab-cal/tape#54]
`from tape import data_utils`
`vocab = {v: k for k, v in data_utils.PFAM_VOCAB.items()}`

and what is PFAM_VOCAB?

**Comment by rmrao** [comment]
I assume this code refers to the old [TAPE repository](https://github.com/songlab-cal/tape-neurips2019). If so, then it refers to the file titled `data_utils.py` in that repository. You can find `PFAM_VOCAB` inside that file.

If you have more questions about the deprecated repo, please open them in that github project.
