### ISSUE TITLE
Fine-Tuning of Bert model

### ISSUE THREAD

**Issue by simolanzi** [songlab-cal/tape#57]
I have a protein sequence dataset (FASTA file) and I want to fine-tune your transformer model adding a task that works on this dataset.

Following the instructions in the "adding_task.py" file, I correctly generated the new task and by entering the command "python adding_task transformer my_new_task", it is executed correctly.

However, when the training phase starts, the following error is reported:

![Untitled](https://user-images.githubusercontent.com/15265107/81917851-005f3180-95d6-11ea-9ce5-4affc5f00241.png)

Apparently, the "J" token is not contained in the IUPAC vocabulary. Checking actually missing, then I tried to enter it manually, but the problem is not resolved, as if the change was not detected.
Is it possible to make such a change? If yes, how can I make the program recognize the change?

And is it possible to force, for example, the function 'convert_to_ids' in tokenizers.py file to assign token J to the token "<unk>" in the IUPAC vocab? Because even this change seems not to work.

**Comment by rmrao** [comment]
You cannot fine-tune a model using a vocabulary that it hasn't already been trained on (or at least, you'll need to modify something to get this to work).

The easiest way to do this would probably be to subclass the tokenizer and overwrite `convert_to_ids` to do exactly that. Then when you create your dataset, instantiate your new tokenizer and pass it in the the dataset.

Alternatively, you can try adding the `J` token to the vocab by adding it to the tokenize and then also calling `resize_token_embeddings` on the model ([here](https://github.com/songlab-cal/tape/blob/ab49d242a81f7a1d0b291507c8a0b0f5fd6d960c/tape/models/modeling_utils.py#L303)).

**Comment by simolanzi** [comment]
Thanks a lot!

**Comment by ddofer** [comment]
Would you mind sharing your code/example finetuned task? (I'm running into issues applying this to my own datasets, would be great to see someone else's code). Thanks!
