### ISSUE TITLE
Corrupted raw remote homology dataset

### ISSUE THREAD

**Issue by wbogud** [songlab-cal/tape#58]
In the raw remote homology dataset, `remote_homology_test_family_holdout.json` is a binary file. Similar to #49 it appears to be an archive which contains `remote_homology_test_fold_holdout.json` and `remote_homology_test_superfamily_holdout.json`.

**Comment by rmrao** [comment]
I don't understand at all how this happened to all these datasets...

Anyway, this should be fixed now. Please reopen if there are still issues.
