### ISSUE TITLE
UniRep model pooled output returns 3800 vector values

### ISSUE THREAD

**Issue by ptynecki** [songlab-cal/tape#60]
Hey,

I would like to use protein embedding based on the pre-trained UniRep model.
I used the code below:

```python
device = 'cuda:0'

model = UniRepModel.from_pretrained('babbler-1900')
model.cuda(device=device)

tokenizer = TAPETokenizer(vocab='unirep')

sequence = 'GCTVEDRCLIGMGAILLNGCVIGSGSLVAAGALITQ'
token_ids = torch.tensor(
    [tokenizer.encode(sequence)],
    device=device
)

output = model(token_ids)

sequence_output = output[0]
pooled_output = output[1]
```

What I discovered is the fact that pooled output shape is X/3800 instead of X/1900 (as I expected). Would you tell me why it's double?

When I used _ProteinBertModel_ with _bert-base_ in the same way I got correct shape.

Thanks for clarification.

Piotr

**Comment by rmrao** [comment]
The pooled output is the concatenation of the hidden state and the carry state of the LSTM. I figured that returning both would allow users to select which they prefer.
