### ISSUE TITLE
Reading output_filename.npz

### ISSUE THREAD

**Issue by simolanzi** [songlab-cal/tape#62]
I tried to produce the file 'output_filename.npz' using the command:

`tape-embed transformer my_input.fasta output_filename.npz bert-base --tokenizer iupac`.

The file is correctly created, but when I try to import it, I can't access the data correctly.

First (following the instruction reported in README file), using the comand: 

`arrays = np.load('output_filename.npz', allow_pickle=True)`, 

the file is correctly loaded. Then, I created a list of both the keys (in my case the protein sequences id) and the values ​​(the dictionaries of the 'pooled' and 'avg' vectors associated with the protein id) :

`keys = list(arrays.keys())` 
`values = []`
`for key in keys:`
`values.append(arrays[key])`

But the values ​​of each key in my case are numpy.arrays of size 0, and not dictionaries as indicated in the README file. I can print it, but I don't have the possibility to access the 'pooled' and 'avg' fields as I would like. What am I doing wrong?

Below are some prints of what I mentioned above:
![Issue](https://user-images.githubusercontent.com/15265107/82480275-d5904400-9ad3-11ea-814b-e5c00c253f68.png)

**Comment by jas-preet** [comment]
Hey!, I was stuck at the same but if you use arrays[key].item(). This should work.

**Comment by rmrao** [comment]
Ah yes - when saved as a numpy file, numpy makes everything into a numpy array. So dictionaries get turned into numpy object arrays. Calling `.item()` should give you the result.
