### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by simolanzi** [songlab-cal/tape#66]
I stopped a training of your 'transformer' model with my language model task and in the 'result' folder, I have several files, including the log file.

Could you give an example of how you can view the results saved inside? Because I tried to open it with tensorboardX, but it turns out not to contain data to show.

Furthermore, I saw that the repo contains a file called 'visualization.py', which I believe is to be used in this area, but I have not understood how to do it.
Thanks a lot!

**Comment by rmrao** [comment]
I actually moved to using Weights & Biases for my visualization a while ago, but I believe the tensorflow logging should still work. For actual visualization you need to run `tensorboard --logdir <path to directory>`. You can find lots of examples on how to use tensorboard online.
