### ISSUE TITLE
Contact Prediction (ProteinNet) raw data download link not working

### ISSUE THREAD

**Issue by nibtehaz** [songlab-cal/tape#67]
Hi, 
First of all thank you so much for this wonderful repository. I've really liked your TAPE project.

Unfortunately, I can't download the raw dataset for Contact Prediction Task. It is showing access denied.

The link provided in your readme.md is [http://s3.amazonaws.com/proteindata/data_raw_pytorch/proteinnet.tar.gz](http://s3.amazonaws.com/proteindata/data_raw_pytorch/proteinnet.tar.gz)

Would you kindly have a look at this.

Thanks.

**Comment by rmrao** [comment]
Sorry about that, should be fixed!

**Comment by nibtehaz** [comment]
Thank you so much for this quick fix.
