### ISSUE TITLE
CUDA out of memory issue with contact map and masked_language_model training

### ISSUE THREAD

**Issue by skyve2012** [songlab-cal/tape#70]
Just wonder if anyone has encountered "CUDA out of memory" issue before? When I tried training contact_prediction model and the masked_language_model with the following batch_size configuration, I received the "CUDA out of memory" error.

For example:

by having the following batch size configuration for masked_language_model:

`Hyperparameters:
		batch_size per backward-pass: 256
		gradient_accumulation_steps: 64
		n_gpu: 4
		batch_size per (gpu * forward-pass): 2`

I receive the following error:

`RuntimeError: CUDA out of memory. Tried to allocate 386.00 MiB (GPU 6; 15.78 GiB total capacity; 14.32 GiB already allocated; 89.44 MiB free; 14.63 GiB reserved in total by PyTorch)`
`RuntimeError: CUDA out of memory. Reduce batch size or increase gradient_accumulation_steps to divide each batch over more forward passes.`

The error asks me to reduce the # of samples per forward pass (which currently is 2 in the above configuration). I tried this as well. However, it only works for masked_language_model training. For the contact_prediction, even if I specify the batch_size per forward pass to be 1. I still get the cuda memory issue. Just wonder has anyone encountered and resolved this issue before? This prevents me from having a larger "batch per forward pass" configuration.

P.S. this seems to be independent of how many GPUs I used, as long as the batch_size per forward pass is greater than 1, The optimization process of the two models will be stopped somewhere in the middle of the training. And this problem happens with or without the "--fp16" flag.

I did some search online and found that some Apex cuda memory leak issue that might be similar to this (not sure though). I also tried using torch.cuda.empty_cache() to empty the unnecessary memory in CUDA during the training (before each forward pass). I did see drops in the memory allocation in GPUs with `watch -n 1 nvidia-smi` (e.g., from 5000MB to 2000MB), however, I still got the same out of memory error during training even the usage of GPU memory in `nvidia-smi` is around 2000MB.

And my current GPU has 16GB memory. By my visual check, usually the training program ends before the actual GPU usage (displayed in nvidia-smi) reaches 16GB and the error is still "CUDA out of memory".

**Comment by rmrao** [comment]
I doubt this is a memory leak. These are simply very large sequences and quite large models. There are some solutions depending on the amount of effort you'd like to put in:

1. For contact prediction, you can modify the prediction head ([here](https://github.com/songlab-cal/tape/blob/8495202d78a5e0a7168702dffb512ce9b1fa7f58/tape/models/modeling_utils.py#L843-L869)) to first downsample the output features before calculating `pairwise_features`. This should reduce memory.
2. You can modify the datasets to randomly subsample the sequences (which is what trRosetta + AlphaFold do) - i.e. select a random portion of the input + target with length < 512, 256, 128, etc. (whichever gets things to fit on GPU).
3. You can add gradient checkpointing to these models to reduce memory footprint.

**Comment by skyve2012** [comment]
Get it. Thanks a lot! I'll try working on these approaches.
