### ISSUE TITLE
UniRep pretrained weights

### ISSUE THREAD

**Issue by fteufel** [songlab-cal/tape#73]
Hi,

I would need some clarification as to what the `babbler-1900` checkpoint is exactly.
Is this the actual UniRep model from the original paper, or just the UniRep architecture trained on Pfam? Internally, the LM task points to Pfam as for every other model.

Reason being I want to evaluate the perplexity of UniRep on some sequences.

**Comment by rmrao** [comment]
This is the actual UniRep model from the original paper, not the UniRep architecture trained on Pfam. We don't have pytorch weights for the UniRep architecture trained on Pfam (although we do have tensorflow weights for that [here](http://s3.amazonaws.com/proteindata/pretrain_weights/unirep_weights.h5)). If you're interested, it should be possible to manually load the weights from the tensorflow save file into the pytorch model (or to use the tensorflow model directly).
