### ISSUE TITLE
How use Huggingface API for Loading Pretrained Models?

### ISSUE THREAD

**Issue by binarywz** [songlab-cal/tape#76]
Hi, thanks for creating this repo, it's really useful. I want to know how use Huggingface API for Loading Pretrained Models?  When I run the example code, the program  reports error.
![1](https://user-images.githubusercontent.com/58714070/87225168-b02a0300-c3bd-11ea-9deb-d34ae72440ca.png)
![2](https://user-images.githubusercontent.com/58714070/87225170-b324f380-c3bd-11ea-87ab-d7271b8321f7.png)

**Comment by rmrao** [comment]
There was recently an update to TAPE that added the `filelock` package as a dependency. You can manually install it or run `pip install -r requirements.txt` on TAPE's requirements file.
