### ISSUE TITLE
Sequence length varies when generating an embeding.

### ISSUE THREAD

**Issue by jas-preet** [songlab-cal/tape#78]
HI,
I am trying to generate the embedding for all amino acids in the sequence. but the embedding it returns has two more amino acids than in the sequence. 
for example I feed a sequence of length 75 I get the embedding of dimension (77,1800).
FYI
I am using this command 
"tape-embed unirep my_input.fasta output_filename.npz babbler-1900 --tokenizer unirep --full_sequence_embed"
Any help will be highly appreciated.

Regards

**Comment by rmrao** [comment]
TAPE and Unirep add start and stop tokens to each sequence, which increases the sequence length by one on either end. You can either use these as part of the average or remove them, it may depend on your application.
