### ISSUE TITLE
Generate Secondary Structure prediction from fasta file directly.

### ISSUE THREAD

**Issue by jas-preet** [songlab-cal/tape#79]
Hi,
I am trying to use your secondary structure prediction model. I am facing problem with running it as an inference. To explain a little more, I am after something like I feed the fasta file to the program and it returns a file with the predicted secondary structure(one-hot prediction model). 

I am facing problem in understanding how to run the "tape-eval transformer secondary_structure results/<path_to_trained_model> --metrics accuracy" as in terms how do I download the trained models. Also, I don't have the labels for the sequence, so how will it  provide me the accuracy metrics without that.

any help will be highly appreciated. 

Regards

**Comment by rmrao** [comment]
We do not provide pretrained weights for the downstream tasks, but you can train a downstream secondary structure model yourself by following the instructions in the README.

`tape-eval` cannot be used for inference on a dataset without labels. You'll have to write your own function to load the model and make the predictions. There's obviously no way to compute accuracy without labeled data.
