### ISSUE TITLE
2 problems - SOLVED

### ISSUE THREAD

**Issue by KarinBrisker** [songlab-cal/tape#8]
Hello, I wanted to let you know that I encountered 2 problems and resolved them for myself, which you may want to update with you.
1) After running the first command I was told "from Bio import SeqIO no module named Bio" - solved with pip install biopython
2) "ValueError: Object arrays cannot be saved when allow_pickle = False"
so I changed source code in tape / utils / utils.py line 283 to include "allow_pickle = True"

Thanks for sharing your code :)

**Comment by rmrao** [comment]
Awesome Karin! Thanks for the investigation.

**Comment by rmrao** [comment]
Fixed by #12.
