### ISSUE TITLE
Training LSTM language model on own data

### ISSUE THREAD

**Issue by kodrzywolek** [songlab-cal/tape#83]
Hi,

First of all, thanks for all the great work put in the repository. 

I plan to train the LSTM language model on my own data, but after reading issue #33, I decided to ask you for guidance first. Is the LSTM code tested and debugged? Do you recommend to use it as it is?

Another thing, is there any Dockerfile or Docker Image with the prepared training environment? 

Thanks for your help!

**Comment by rmrao** [comment]
If you really want an LSTM model I'd recommend looking at the SeqVec model from the Rostlab (see [here](https://github.com/rostlab/SeqVec)). TAPE's LSTM model plausibly will work but that one is much more likely to.
