### ISSUE TITLE
How to declare "ProteinBertModel" model without pretrained ?

### ISSUE THREAD

**Issue by iampartho** [songlab-cal/tape#89]
I have been trying to use your "ProteinBertModel" for my project but for my project the model needed to be modified and as a matter I cannot declare the model by using the command "ProteinBertModel.from_pretrained('bert-base')" , I was not been able to find any other declaring method , so I was wondering if anyone could help me with the line of code that loads the "ProteinBertModel" without loading the pretrained weights. Thanks.

**Comment by rmrao** [comment]
```python
from tape.models import ProteinBertModel, ProteinBertConfig

config = ProteinBertConfig()
model = ProteinBertModel(config)
```

**Comment by iampartho** [comment]
Thank you very much
