### ISSUE TITLE
Vocabulary used for Pre-Trained BERT Model

### ISSUE THREAD

**Issue by simolanzi** [songlab-cal/tape#90]
Hi, I wanted to ask if it was possible to have information on the vocabulary you used for the pre-training of the Transformer-based model (ProteinBertModel).

I learned from your paper that you used the Pfam dataset and the masked-token technique, but I did not understand if you also use the IUPAC vocabulary or another (possibly larger) for the Transformer pre-training.

Thanks for your help.

**Comment by rmrao** [comment]
It is the IIUPAC vocab defined in `tape/tokenizers.py`.
