### ISSUE TITLE
Make Bert Large available as pretrained models

### ISSUE THREAD

**Issue by changecreator** [songlab-cal/tape#95]
Hi :),

thank you for the pre-trained bert-base model. 

I was wondering if you could make a pre-trained bert-large available as well, as it is might perform better on the PPI and Enzyme Classfication tasks I'm working on currently.

**Comment by rmrao** [comment]
Hey - unfortunately, we don't have the compute to make something like that available. Fortunately, other people do and have done so!

I'd suggest checking out ESM (https://github.com/facebookresearch/esm) or ProtTrans (https://github.com/agemagician/ProtTrans).
