### ISSUE TITLE
Where can I download the training and testing for the GFP fluorescence task? 

### ISSUE THREAD

**Issue by PraljakReps** [songlab-cal/tape#99]
Hello, 

Awesome repository! Quick question: since this link (http://s3.amazonaws.com/proteindata/data_raw_pytorch/fluorescence.tar.gz) for downloading the raw GFP fluorescence data seems only to download the validation dataset (~1.34MB), where can I download the raw training and testing data?

**Comment by rmrao** [comment]
I don't seem to be able to reproduce this issue. Are you sure you uncompressed the data? The compressed data is in fact ~1.34 MB but if you untar and uncompress you should see all three files.

**Comment by PraljakReps** [comment]
> I don't seem to be able to reproduce this issue. Are you sure you uncompressed the data? The compressed data is in fact ~1.34 MB but if you untar and uncompress you should see all three files.

Thank you for the fast response! On a Windows machine, I had some initial issues on my end, but everything is fine now.
